name: Release frontend
on:
  push:
    branches:
      - main
    paths:
      - frontend/**

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: Install packages
        working-directory: frontend
        run: npm install
      - name: "Build and deploy frontend"
        working-directory: frontend
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DREAMBOOK_713 }}"
          channelId: live
          entryPoint: frontend
          projectId: dreambook-713
